### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-quebec#21]
La légende cache le spinner...

![image](https://user-images.githubusercontent.com/7397743/205965516-890bfa19-acf8-4a6a-b3cd-6f9b74aea324.png)

a droite sur l'image.

**Comment by mneige** [comment]
On peut remettre le spinner au milieu de la page/carte.

**Comment by mneige** [comment]
https://github.com/infra-geo-ouverte/igo2-quebec/commit/c426f452b4bb311933b6ab871dfdaa1f76dfdf8a
